### ISSUE TITLE
Suggestion: Manually add new comics within app

### ISSUE THREAD

**Issue by ysadalawa** [oseparovic/comic_selectors#95]
Is there any way to introduce a feature for users to manually add new comics within the app itself, rather than waiting for commits to go into production?

**Comment by oseparovic** [comment]
Likely not. All code changes have to be moderated and approved otherwise low quality or malicious code could be included unfortunately. Sorry to disappoint

**Comment by MadameMinty** [comment]
I'd like to suggest an option to add JSON of a comic into the app privately to make it easy to verify if all selectors can be handled by the app.

Usecase: here https://github.com/oseparovic/comic_selectors/issues/96 Maximumble has "#comic > a > img" selector for images, except the last strip: "#comic > img". I'd like the possibility to paste my JSON with "#comic" selector to check if that's sufficient for the app to display the image correctly.

**Comment by oseparovic** [comment]
You can test your code using this site https://try.jsoup.org/. All you have to do is go to the comic site page you want to test, right click on the page and click "view source". Then you can copy paste all this html into the "input html" section on the jsoup site and put the selector you wish to test in the "CSS Query" text field.

For your linked question - "**>**" indicates a direct child. This means that if you're on the last comic page in which the image isn't wrapped in an anchor tag <a>, #comic > a > img will fail. This is because the query is explicitly looking for an <img> that's in an <a> anchor that's in an element with id #comic. You can work around this by simply querying "#comic img" which looks for ALL img tags inside the element with id #comic (regardless of whether they're the first descendant or the nth descendant). By default the app selects the first match of a query and since #comic seems to always have only 1 img this should work on all pages.

**Comment by MadameMinty** [comment]
I wasn't sure if you're maybe using some extra hacks that https://try.jsoup.org/ doesn't. Since apparently not, then I'll stick to that website, thanks! This clarifies everything.

Didn't think of "#comic img". Useful! I'll update the selectors for Maximumble in a minute :)
